---
spring:
  config:
    import: classpath:application-common.yml
---
spring:
  application:
    name: kafka-cache-killer
  kafka:
    producer:
      # 發送端資料壓縮演算法
      compression-type: zstd
      # 發送資料 key 的序列化器
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      # 發送資料 value 的序列化器
      value-serializer: ${producer_value_serializer:org.springframework.kafka.support.serializer.JsonSerializer}
      # 預設無限次數 , 應設定合理 retry 次數
      retries: 3
      properties:
        # 發送端暫存 partition 資料未達 batch-size 值 , 但從第一筆開始等待發送時間已超過此毫秒數 , 依然進行發送
        linger:
          ms: 5
    listener:
      idle-between-polls: 1s
    consumer:
      # k8s 上建議使用 pod name
      group-id: ${spring_kafka_consumer_group_id:${spring.application.name}-${random.uuid}}
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      # 避免 kafka 資料格式問題 , 使用這個反序列化器 , 將失敗的轉成 null , 在 listener 中進行處理
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      # 自動 commit 不建議使用 , 容易造成漏消費
      enable-auto-commit: ${spring_kafka_consumer_enable_auto_commit:false}
      auto-offset-reset: latest
      properties:
        spring:
          deserializer:
            key:
              delegate:
                class: org.apache.kafka.common.serialization.StringDeserializer
            value:
              delegate:
                class: ${consumer_value_deserializer:org.springframework.kafka.support.serializer.JsonDeserializer}
          json:
            trusted:
              packages: '*'
            value:
              default:
                type: com.redhat.kafkacachekiller.cache.CacheKillerInfo
    template:
      default-topic: cache-kill
    bootstrap-servers: ${spring_kafka_bootstrap_servers:localhost:29092}
server:
  port: 7777
cache:
  kill:
    endpoint: /cache/kill
    wait-time:
      value: 2
      unit: seconds
      enabled: ${cache_kill_wait_time_enabled:false}