spring:
  config:
    import: classpath:application-common.yml
---
spring:
  application:
    name: async-mail-sender-consumer
  kafka:
    consumer:
      # consumer group id
      group-id: send-mail-group
      # 消費資料 key 的反序列化器
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      # 消費資料 value 的反序列化器
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      # 手動 commit offset (搭配 MANUAL_IMMEDIATE ack mode)
      enable-auto-commit: false
      # 當沒有 offset 時從頭開始消費
      auto-offset-reset: latest
      properties:
        spring:
          deserializer:
            key:
              delegate:
                class: org.apache.kafka.common.serialization.StringDeserializer
            value:
              delegate:
                class: ${consumer_value_deserializer:org.springframework.kafka.support.serializer.JsonDeserializer}
          json:
            trusted:
              packages: com.iisigroup.df.model
            value:
              default:
                type: com.iisigroup.df.model.SendMailEvent
    listener:
      ack-mode: record
    template:
      default-topic: send-mail-topic
    bootstrap-servers: ${spring_kafka_bootstrap_servers:localhost:29092}
  mail:
    host: ${spring_mail_host:smtp.gmail.com}
    port: ${spring_mail_port:587}
    username: ${spring_mail_username:zxc81906119@gmail.com}
    password: ${spring_mail_password:vwpnmsvakojxweoq}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.connectiontimeout: 5000
      mail.smtp.timeout: 5000
      mail.smtp.writetimeout: 5000
app:
  mail:
    from: ${app_mail_from:${spring.mail.username}}
server:
  port: 7799